name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Zip Audi Setups
        run: |
          rm -rf build/audi90gto-setups.zip
          cd public/setups/audi90gto && zip -r ../../../build/audi90gto-setups.zip ./* && cd ../../../

      - name: Zip Nissan Setups
        run: |
          rm -rf build/nissangtpzxt-setups.zip
          cd public/setups/nissangtpzxt && zip -r ../../../build/nissangtpzxt-setups.zip ./* && cd ../../../

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: build
